# Introduction to NumPy

In [1]:
import numpy as np

## Probelm 1

In [2]:
A = np.array([[3, -1, 4], 
              [1, 5, -9]])
B = np.array([[2, 6, -5, 3], 
              [5, -8, 9, 7], 
              [9, -3, -2, -3]]) 

There are two main ways to perform matrix multiplication in NumPy:
1. with NumPy's dot() function (np.dot(A, B)), 
2. with the @ operator (A @ B).

In [3]:
np.dot(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [4]:
A @ B

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [5]:
A = np.array([[3, 1, 4], 
              [1, 5, 9],
              [-5, 3, 1]])
- A @ A @ A + 9 * A @ A - 15 * A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

This is a demonstration of the Cayley-Hamilton theorem: $p(A)=0$, where $p(.)$ is the characteristic polynomial for the matrix $A$. 

## Problem 3

In [6]:
A = np.triu(np.ones((7, 7)))
B = np.tril((-1)*np.ones((7, 7))) + np.triu(5*np.ones((7, 7))) - 5 * np.eye(7)
print(A)
print(B)

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[-1.  5.  5.  5.  5.  5.  5.]
 [-1. -1.  5.  5.  5.  5.  5.]
 [-1. -1. -1.  5.  5.  5.  5.]
 [-1. -1. -1. -1.  5.  5.  5.]
 [-1. -1. -1. -1. -1.  5.  5.]
 [-1. -1. -1. -1. -1. -1.  5.]
 [-1. -1. -1. -1. -1. -1. -1.]]


In [7]:
C = A @ B @ A
C = C.astype(np.int64)
print(C)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


## Problem 4
Write a function that accepts a single array as input. Make a copy of the array,
then use fancy indexing to set all negative entries of the copy to 0. Return the copy.

In [8]:
def nonneg(x):
    mask = x < 0
    x[mask] = 0
    return x

## Problem 5

In [9]:
A = np.arange(6).reshape((3,2)).T
B = np.tril(3*np.ones(3))
C = -2*np.eye(3)
V1 = np.hstack((np.zeros((3,3)), A.T, np.eye(3)))
V2 = np.hstack((A, np.zeros((2,2)), np.zeros((2,3))))
V3 = np.hstack((B, np.zeros((3,2)), C))
np.vstack((V1, V2, V3))

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

## Problem 6
Write a function than accepts a matrix (as a 2-D array). Divide each row of the matrix by the row sum and return the new row-stochastic matrix. Use array broadcasting and the axis argument instead of a loop.

In [10]:
def rowsto(x):
    rowsum = x.sum(axis=1).reshape(-1,1)
    return x/rowsum

## Problem 7

In [11]:
grid = np.load("grid.npy")

In [12]:
hormax = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
vermax = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
rdgmax = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
ldgmax = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
winner = np.max([hormax, vermax, rdgmax, ldgmax])
print(winner)

70600674
