# Numerical Integration

## Exercise 2.1 Three Newton-Cotes Methods

In [1]:
import numpy as np

In [2]:
def newtoncotes(g, a, b, N, method):
    if method == 'midpoint':
        sum = 0
        interval = np.linspace(a, b, N + 1)
        step = (b - a) / N
        for i in range(0, N):
            left = interval[i]
            right = interval[i+1]
            midpoint = (left + right) / 2
            sum = sum + g(midpoint)*step
            
    elif method == 'trapezoid':
        sum = 0
        interval = np.linspace(a, b, N + 1)
        step = (b - a) / N
        for i in range(0, N):
            left = interval[i]
            right = interval[i+1]
            sum = sum + (g(left) + g(right))*step/2
    
    elif method == 'Simpsons':
        sum = 0
        interval = np.linspace(a, b, N + 1)
        step = (b - a) / N
        for i in range(0, N):
            left = interval[i]
            right = interval[i+1]
            midpoint = (left + right) / 2
            sum = sum + (g(left)+4*g(midpoint)+g(right))*step/6
    
    else:
        print("Please specify a valid method from 'midpoint', 'trapezoid', 'Simpsons'.")
        
    return sum

In [3]:
g = lambda x: 0.1*x**4 -1.5*x**3 + 0.53*x**2 + 2*x + 1
a = -10
b = 10
N = 100

print("Analytical: 4373.33")
print("Midpoint: " + str(newtoncotes(g, a, b, N, 'midpoint')))
print("Trapezoid: " + str(newtoncotes(g, a, b, N, 'trapezoid')))
print("Simpsons: " + str(newtoncotes(g, a, b, N, 'Simpsons')))

Analytical: 4373.33
Midpoint: 4371.964759999997
Trapezoid: 4376.070559999995
Simpsons: 4373.333359999999


## Exercise 2.2 Newton-Cotes Discrete Approximation of Normal

In [4]:
import scipy.stats

In [5]:
def ncnormal(mu, sd, N, k):
    Z = np.linspace(mu-k*sd, mu+k*sd, N)
    w = np.zeros(N)
    
    for i in range(0, N):
        if i == 0:
            w[i] = scipy.stats.norm.cdf((Z[0]+Z[1])/2, mu, sd)
        elif i == N-1:
            w[i] = 1 - scipy.stats.norm.cdf((Z[N-2]+Z[N-1])/2, mu, sd)
        else:
            w[i] = scipy.stats.norm.cdf((Z[i]+Z[i+1])/2, mu, sd) - \
            scipy.stats.norm.cdf((Z[i-1]+Z[i])/2, mu, sd)
        
    return Z, w

In [6]:
mu = 0
sd = 1
k = 3
N = 11

ncnormal(mu, sd, N, k)

(array([-3. , -2.4, -1.8, -1.2, -0.6,  0. ,  0.6,  1.2,  1.8,  2.4,  3. ]),
 array([0.00346697, 0.01439745, 0.04894278, 0.11725292, 0.19802845,
        0.23582284, 0.19802845, 0.11725292, 0.04894278, 0.01439745,
        0.00346697]))

## Exercise 2.3 Discrete Approximation of Log-Normal

In [7]:
def nclognorm(mu, sd, N, k):
    Z, w = ncnormal(mu, sd, N, k)
    A = np.exp(Z)
    return A, w

In [8]:
nclognorm(mu, sd, N, k)

(array([ 0.04978707,  0.09071795,  0.16529889,  0.30119421,  0.54881164,
         1.        ,  1.8221188 ,  3.32011692,  6.04964746, 11.02317638,
        20.08553692]),
 array([0.00346697, 0.01439745, 0.04894278, 0.11725292, 0.19802845,
        0.23582284, 0.19802845, 0.11725292, 0.04894278, 0.01439745,
        0.00346697]))

## Exercise 2.4 Approximated Mean of Log-Normal

In [9]:
mu = 10.5
sd = 0.8
N = 11
k = 3

Y, w = nclognorm(mu, sd, N, k)
print("Approximation: " + str(np.dot(Y,w))) 
print("Analytical: " + str(np.exp(mu+sd**2/2))) 

Approximation: 50352.456192765916
Analytical: 50011.087008521754


## Exercise 3.1 Gaussian Quadrature

In [10]:
def quadsys(x):
    w1, w2, w3, x1, x2, x3 = x
    z0 = w1 + w2 + w3 - 20
    z1 = w1*x1 + w2*x2 + w3*x3 - 0
    z2 = w1*x1**2 + w2*x2**2 + w3*x3**2 - 2000/3
    z3 = w1*x1**3 + w2*x2**3 + w3*x3**3 - 0
    z4 = w1*x1**4 + w2*x2**4 + w3*x3**4 - 40000
    z5 = w1*x1**5 + w2*x2**5 + w3*x3**5 - 0
    return z0, z1, z2, z3, z4, z5

In [11]:
import scipy.optimize
w1, w2, w3, x1, x2, x3 = scipy.optimize.root(quadsys,[0,0,0,-10,0,10]).x
print("Gaussian Quadrature Approximation:")
w1*g(x1) + w2*g(x2) + w3*g(x3)

Gaussian Quadrature Approximation:


4373.333333343174

## Exercise 3.2 Python Gaussian quadrature Command

In [12]:
import scipy.integrate
scipy.integrate.quad(g,a,b)

(4373.333333333334, 8.109531705284936e-11)

## Exercise 4.1 Monte Carlo Integration

In [13]:
import scipy.stats as sts

In [14]:
def mcinteg(g, Omega, N):
    V = (Omega[0][1] - Omega[0][0]) * (Omega[1][1] - Omega[1][0])
    np.random.seed(seed=25)
    x = np.random.uniform(Omega[0][0], Omega[0][1], N)
    y = np.random.uniform(Omega[1][0], Omega[1][1], N)
    val = g(x, y)
    return V * np.sum(val) / N

In [15]:
g = lambda x, y: (x**2 + y**2) <= 1
Omega = [[-1,1],[-1,1]]

diff = 1
N = 0
while diff > 1e-04:
    N += 1
    diff = abs(mcinteg(g, Omega, N) - 3.1415)
print("The smallest number of draws to match the 4th decimal: " + str(N))
print("The approximated pi: " + str(mcinteg(g, Omega, N)))

The smallest number of draws to match the 4th decimal: 657
The approximated pi: 3.141552511415525
